server:
  port: 8084
spring:
  application:
    name: webfluxfilmsdb
  r2dbc:
#    url: r2dbc:pool:postgres://localhost:5433/postgres
    url: r2dbc:postgresql://host.docker.internal:5433/postgres
    username: postgres
    password: postgres
  flyway:
    url: jdbc:postgresql://localhost:5433/postgres
    locations: classpath:db/migration
    user: postgres
    password: postgres
    enabled: true
    baseline-on-migrate: true
logging:
  level:
    org.springframework.web: DEBUG

jwt:
  password:
    encoder:
      secret: FZK2DZ82odqS13e8aENggaMbb_fAkl-nJL4AEVBX43g
      iteration: 64
      keylength: 256
  secret: b5f59337a612a2a7dc07328f3e7d1a04722967c7f06df20a499a7d3f91ff2a7e
  expiration: 86400
  issuer: cleavest

